blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: Per domande generiche su Home Assistant non specifiche dell'integrazione Iliad Italia.
